name: gen-EM

dependencies:
  - python=3.8
  - jupyter=1.00
  - matplotlib=3.1.3
  - pandas=1.0.3
  - pip=20.0.2
  - pip:
    - wkw==0.1.2
    - torch==1.5.0
    - torchvision==0.6.0
    - tensorboard==2.2.1

