name: genEM3
channels:
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.5.0
  - cudatoolkit=10.1
  - jupyter=1.00
  - matplotlib=3.1.3
  - pandas=1.0.3
  - ipywidgets=7.5.1
  - pip=20.0.2
  - scipy=1.5.2
  - pillow
  - pip:
    - wkw==0.1.2
    - tensorboard==2.2.1
    - pytest==6.0.1
    - wkskel==0.0.2
    - pigeon-jupyter==0.1.0
